<?xml version="1.0" encoding="utf-8"?><Database Name="TAISANDAMBAO_PRO" Class="AssetDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=KIEPDATRANG\SQLEXPRESS;Initial Catalog=TAISANDAMBAO_PRO;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="gMVVMConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ZOO_BENH" Member="ZOO_BENHs">
    <Type Name="ZOO_BENH">
      <Column Name="MaBenh" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenBenh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ThoiGianBenh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TrieuChung" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="NOTES" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="RECORD_STATUS" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="MAKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CREATE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AUTH_STATUS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CHECKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="APPROVE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ZOO_TYPE" Member="ZOO_TYPEs">
    <Type Name="ZOO_TYPE">
      <Column Name="MaLoai" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Loai" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Mota" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="NOTES" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="RECORD_STATUS" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="MAKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CREATE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AUTH_STATUS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CHECKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="APPROVE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ZOO_CHOAN" Member="ZOO_CHOANs">
    <Type Name="ZOO_CHOAN">
      <Column Name="MaChoAn" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaChuong" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="MaKhauPhanAn" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="NOTES" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="RECORD_STATUS" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="MAKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CREATE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AUTH_STATUS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CHECKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="APPROVE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ZOO_CHUONG" Member="ZOO_CHUONGs">
    <Type Name="ZOO_CHUONG">
      <Column Name="MaChuong" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaLoaiChuong" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="MaLoaiDV" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="TenChuong" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoLuongHienTai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoLuongToiDa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="NOTES" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="RECORD_STATUS" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="MAKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CREATE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AUTH_STATUS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CHECKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="APPROVE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ZOO_DIEUTRI" Member="ZOO_DIEUTRIs">
    <Type Name="ZOO_DIEUTRI">
      <Column Name="MaDieuTri" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaBenh" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="MaDongVat" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="NgayDieuTri" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayBenh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="NOTES" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="RECORD_STATUS" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="MAKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CREATE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AUTH_STATUS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CHECKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="APPROVE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ZOO_DONGVAT" Member="ZOO_DONGVATs">
    <Type Name="ZOO_DONGVAT">
      <Column Name="MaDongVat" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenDongVat" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TenKhoaHoc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaLoaiDV" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="MaMe" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="MaCha" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="MaChuong" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Mau" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="CanNang" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ChieuCao" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ChieuDai" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayNhapVe" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="HinhThucGiamSat" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NoiXuatXu" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NoiCuTru" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TuoiTho" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NOTES" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="RECORD_STATUS" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="MAKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CREATE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AUTH_STATUS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CHECKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="APPROVE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ZOO_DONTHUOC" Member="ZOO_DONTHUOCs">
    <Type Name="ZOO_DONTHUOC">
      <Column Name="MaDonThuoc" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaBenh" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="MaThuoc" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="NOTES" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="RECORD_STATUS" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="MAKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CREATE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AUTH_STATUS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CHECKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="APPROVE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ZOO_HOSO" Member="ZOO_HOSOs">
    <Type Name="ZOO_HOSO">
      <Column Name="MaHoSo" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenHoSo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LoaiHoSo" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="NOTES" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="RECORD_STATUS" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="MAKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CREATE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AUTH_STATUS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CHECKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="APPROVE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ZOO_KHAUPHANAN" Member="ZOO_KHAUPHANANs">
    <Type Name="ZOO_KHAUPHANAN">
      <Column Name="MaKhauPhanAn" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaLoai" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="MaTrangThai" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="ThoiGianAn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NOTES" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="RECORD_STATUS" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="MAKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CREATE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AUTH_STATUS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CHECKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="APPROVE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="ZOO_KHAUPHANAN_ZOO_THUCDON" Member="ZOO_THUCDONs" ThisKey="MaKhauPhanAn" OtherKey="MaKhauPhanAn" Type="ZOO_THUCDON" />
    </Type>
  </Table>
  <Table Name="dbo.ZOO_LOAIDV" Member="ZOO_LOAIDVs">
    <Type Name="ZOO_LOAIDV">
      <Column Name="MaLoai" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLoai" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Loai" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NOTES" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="RECORD_STATUS" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="MAKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CREATE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AUTH_STATUS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CHECKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="APPROVE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ZOO_LOTHUOC" Member="ZOO_LOTHUOCs">
    <Type Name="ZOO_LOTHUOC">
      <Column Name="MaLo" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaThuoc" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="SoLo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="NgaySanXuat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayHetHan" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NOTES" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="RECORD_STATUS" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="MAKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CREATE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AUTH_STATUS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CHECKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="APPROVE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ZOO_NHANVIEN" Member="ZOO_NHANVIENs">
    <Type Name="ZOO_NHANVIEN">
      <Column Name="MaNhanVien" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LoaiNhanVien" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TenNhanVien" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="CMND" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="NgayVaoLam" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="NOTES" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="RECORD_STATUS" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="MAKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CREATE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AUTH_STATUS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CHECKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="APPROVE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ZOO_PHANCONGCHOAN" Member="ZOO_PHANCONGCHOANs">
    <Type Name="ZOO_PHANCONGCHOAN">
      <Column Name="MaPhanCong" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNhanVien" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="MaChoAn" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Mota" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="NgayChoAn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="NOTES" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="RECORD_STATUS" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="MAKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CREATE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AUTH_STATUS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CHECKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="APPROVE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ZOO_PHANCONGDIEUTRI" Member="ZOO_PHANCONGDIEUTRIs">
    <Type Name="ZOO_PHANCONGDIEUTRI">
      <Column Name="MaPhanCong" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNhanVien" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="MaDieuTri" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="NOTES" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="RECORD_STATUS" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="MAKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CREATE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AUTH_STATUS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CHECKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="APPROVE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ZOO_PHANCONGVESINH" Member="ZOO_PHANCONGVESINHs">
    <Type Name="ZOO_PHANCONGVESINH">
      <Column Name="MaPhanCong" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNhanVien" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="MaChuong" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Mota" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayLam" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="NOTES" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="RECORD_STATUS" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="MAKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CREATE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AUTH_STATUS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CHECKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="APPROVE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ZOO_PHIEUDATTHUCAN" Member="ZOO_PHIEUDATTHUCANs">
    <Type Name="ZOO_PHIEUDATTHUCAN">
      <Column Name="MaPhieuDat" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaThucAn" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="NgayDat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NOTES" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="RECORD_STATUS" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="MAKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CREATE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AUTH_STATUS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CHECKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="APPROVE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ZOO_PHIEUDATTHUOC" Member="ZOO_PHIEUDATTHUOCs">
    <Type Name="ZOO_PHIEUDATTHUOC">
      <Column Name="MaPhieuDat" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaThuoc" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="NgayDat" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NOTES" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="RECORD_STATUS" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="MAKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CREATE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AUTH_STATUS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CHECKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="APPROVE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ZOO_PHIEUNHAPTHUCAN" Member="ZOO_PHIEUNHAPTHUCANs">
    <Type Name="ZOO_PHIEUNHAPTHUCAN">
      <Column Name="MaPhieuNhap" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaThucAn" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NgayNhap" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NOTES" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="RECORD_STATUS" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="MAKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CREATE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AUTH_STATUS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CHECKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="APPROVE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ZOO_PHIEUNHAPTHUOC" Member="ZOO_PHIEUNHAPTHUOCs">
    <Type Name="ZOO_PHIEUNHAPTHUOC">
      <Column Name="MaPhieuNhap" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaLo" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayNhap" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NOTES" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="RECORD_STATUS" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="MAKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CREATE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AUTH_STATUS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CHECKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="APPROVE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ZOO_PHIEUXUATTHUCAN" Member="ZOO_PHIEUXUATTHUCANs">
    <Type Name="ZOO_PHIEUXUATTHUCAN">
      <Column Name="MaPhieuXuat" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaThucAn" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TinhTrang" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="NgayXuat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NOTES" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="RECORD_STATUS" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="MAKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CREATE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AUTH_STATUS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CHECKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="APPROVE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ZOO_PHIEUXUATTHUOC" Member="ZOO_PHIEUXUATTHUOCs">
    <Type Name="ZOO_PHIEUXUATTHUOC">
      <Column Name="MaPhieuXuat" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="MaLo" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="NgayXuat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NOTES" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="RECORD_STATUS" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="MAKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CREATE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AUTH_STATUS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CHECKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="APPROVE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ZOO_STATUS" Member="ZOO_STATUS">
    <Type Name="ZOO_STATUS">
      <Column Name="MaTrangThai" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenTrangThai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LoaiTrangThai" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NOTES" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="RECORD_STATUS" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="MAKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CREATE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AUTH_STATUS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CHECKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="APPROVE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ZOO_THUCAN" Member="ZOO_THUCANs">
    <Type Name="ZOO_THUCAN">
      <Column Name="MaThucAn" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LoaiThucAn" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="DonViTinh" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="TenThucAn" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="NgayNhap" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="HamLuongDinhDuong" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NOTES" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="RECORD_STATUS" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="MAKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CREATE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AUTH_STATUS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CHECKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="APPROVE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ZOO_THUCDON" Member="ZOO_THUCDONs">
    <Type Name="ZOO_THUCDON">
      <Column Name="MaThucDon" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaThucAn" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="MaKhauPhanAn" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="NOTES" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="RECORD_STATUS" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="MAKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CREATE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AUTH_STATUS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CHECKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="APPROVE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="ZOO_KHAUPHANAN_ZOO_THUCDON" Member="ZOO_KHAUPHANAN" ThisKey="MaKhauPhanAn" OtherKey="MaKhauPhanAn" Type="ZOO_KHAUPHANAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ZOO_THUOC" Member="ZOO_THUOCs">
    <Type Name="ZOO_THUOC">
      <Column Name="MaThuoc" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenThuoc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DonViTinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="NOTES" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="RECORD_STATUS" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="MAKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CREATE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AUTH_STATUS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CHECKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="APPROVE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.ZOO_PHIEUNHAPTHUOC_Upd" Method="ZOO_PHIEUNHAPTHUOC_Upd">
    <Parameter Name="p_MaPhieuNhap" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="p_MaLo" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="p_SoLuong" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_NgayNhap" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="p_NOTES" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="p_RECORD_STATUS" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="p_MAKER_ID" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="p_CREATE_DT" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="p_AUTH_STATUS" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="p_CHECKER_ID" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="p_APPROVE_DT" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="ZOO_PHIEUNHAPTHUOC_UpdResult">
      <Column Name="Result" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="MaPhieuNhap" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="ErrorDesc" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ZOO_LOTHUOC_Ins" Method="ZOO_LOTHUOC_Ins">
    <Parameter Name="p_MaThuoc" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="p_SoLo" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="p_NgaySanXuat" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="p_NgayHetHan" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="p_SoLuong" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_NOTES" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="p_RECORD_STATUS" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="p_MAKER_ID" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="p_CREATE_DT" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="p_AUTH_STATUS" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="p_CHECKER_ID" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="p_APPROVE_DT" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="ZOO_LOTHUOC_InsResult">
      <Column Name="Result" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="MaLo" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="ErrorDesc" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.ZOO_LOTHUOC_Search" Method="ZOO_LOTHUOC_Search">
    <Parameter Name="p_MaLo" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="p_MaThuoc" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="p_TenThuoc" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="p_SoLo" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="p_NgaySanXuat" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="p_NgayHetHan" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="p_TOP" Type="System.Int32" DbType="Int" />
    <ElementType Name="ZOO_LOTHUOC_SearchResult">
      <Column Name="MaLo" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="MaThuoc" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="SoLo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="NgaySanXuat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayHetHan" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NOTES" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="RECORD_STATUS" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="MAKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CREATE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AUTH_STATUS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CHECKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="APPROVE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TenThuoc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DonViTinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ZOO_LOTHUOC_Upd" Method="ZOO_LOTHUOC_Upd">
    <Parameter Name="p_MaLo" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="p_MaThuoc" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="p_SoLo" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="p_NgaySanXuat" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="p_NgayHetHan" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="p_SoLuong" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_NOTES" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="p_RECORD_STATUS" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="p_MAKER_ID" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="p_CREATE_DT" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="p_AUTH_STATUS" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="p_CHECKER_ID" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="p_APPROVE_DT" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="ZOO_LOTHUOC_UpdResult">
      <Column Name="Result" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="MaLo" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="ErrorDesc" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ZOO_PHIEUNHAPTHUOC_Ins" Method="ZOO_PHIEUNHAPTHUOC_Ins">
    <Parameter Name="p_MaLo" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="p_SoLuong" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_NgayNhap" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="p_NOTES" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="p_RECORD_STATUS" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="p_MAKER_ID" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="p_CREATE_DT" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="p_AUTH_STATUS" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="p_CHECKER_ID" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="p_APPROVE_DT" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="ZOO_PHIEUNHAPTHUOC_InsResult">
      <Column Name="Result" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="MaPhieuNhap" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="ErrorDesc" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.ZOO_PHIEUNHAPTHUOC_Search" Method="ZOO_PHIEUNHAPTHUOC_Search">
    <Parameter Name="p_MaPhieuNhap" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="p_TenThuoc" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="p_NgayNhap" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="p_TOP" Type="System.Int32" DbType="Int" />
    <ElementType Name="ZOO_PHIEUNHAPTHUOC_SearchResult">
      <Column Name="MaPhieuNhap" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="MaLo" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayNhap" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NOTES" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="RECORD_STATUS" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="MAKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CREATE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AUTH_STATUS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CHECKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="APPROVE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TenThuoc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DonViTinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoLo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ZOO_BAOCAOTONKHO_Search" Method="ZOO_BAOCAOTONKHO_Search">
    <Parameter Name="p_MaThuoc" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="p_TenThuoc" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="p_NgayHetHan" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="p_TOP" Type="System.Int32" DbType="Int" />
    <ElementType Name="ZOO_BAOCAOTONKHO_SearchResult">
      <Column Name="TenThuoc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoLo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DonViTinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayHetHan" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ZOO_THUOC_Upd" Method="ZOO_THUOC_Upd">
    <Parameter Name="p_MaThuoc" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="p_TenThuoc" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="p_DonViTinh" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="p_TinhTrang" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="p_MoTa" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="p_NOTES" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="p_RECORD_STATUS" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="p_MAKER_ID" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="p_CREATE_DT" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="p_AUTH_STATUS" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="p_CHECKER_ID" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="p_APPROVE_DT" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="ZOO_THUOC_UpdResult">
      <Column Name="Result" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="MaThuoc" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="ErrorDesc" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ZOO_THUOC_Ins" Method="ZOO_THUOC_Ins">
    <Parameter Name="p_TenThuoc" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="p_DonViTinh" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="p_TinhTrang" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="p_MoTa" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="p_NOTES" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="p_RECORD_STATUS" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="p_MAKER_ID" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="p_CREATE_DT" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="p_AUTH_STATUS" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="p_CHECKER_ID" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="p_APPROVE_DT" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="ZOO_THUOC_InsResult">
      <Column Name="Result" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="MaThuoc" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="ErrorDesc" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.ZOO_THUOC_Search" Method="ZOO_THUOC_Search">
    <Parameter Name="p_MaThuoc" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="p_TenThuoc" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="p_TinhTrang" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="p_TOP" Type="System.Int32" DbType="Int" />
    <ElementType Name="ZOO_THUOC_SearchResult">
      <Column Name="MaThuoc" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="TenThuoc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DonViTinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="NOTES" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="RECORD_STATUS" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="MAKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CREATE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AUTH_STATUS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CHECKER_ID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="APPROVE_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>