//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gMVVM.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AssCommonResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public AssCommonResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gMVVM.Resources.AssCommonResource", typeof(AssCommonResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Bank.
        /// </summary>
        public static string AccountBank {
            get {
                return ResourceManager.GetString("AccountBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Addr {
            get {
                return ResourceManager.GetString("Addr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agrument Id.
        /// </summary>
        public static string Agr_ID {
            get {
                return ResourceManager.GetString("Agr_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amort Acctno.
        /// </summary>
        public static string Amort_Acctno {
            get {
                return ResourceManager.GetString("Amort_Acctno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amort Rate.
        /// </summary>
        public static string AmortRate {
            get {
                return ResourceManager.GetString("AmortRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argrument Code.
        /// </summary>
        public static string Arg_Code {
            get {
                return ResourceManager.GetString("Arg_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argrument Id.
        /// </summary>
        public static string Arg_ID {
            get {
                return ResourceManager.GetString("Arg_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argrument Name.
        /// </summary>
        public static string Arg_Name {
            get {
                return ResourceManager.GetString("Arg_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ass Cat.
        /// </summary>
        public static string AssCat {
            get {
                return ResourceManager.GetString("AssCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Acctno.
        /// </summary>
        public static string Asset_Acctno {
            get {
                return ResourceManager.GetString("Asset_Acctno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auth Status.
        /// </summary>
        public static string AuthStatus {
            get {
                return ResourceManager.GetString("AuthStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch code.
        /// </summary>
        public static string BranchCode {
            get {
                return ResourceManager.GetString("BranchCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Id.
        /// </summary>
        public static string BranchID {
            get {
                return ResourceManager.GetString("BranchID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Name.
        /// </summary>
        public static string BranchName {
            get {
                return ResourceManager.GetString("BranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch type.
        /// </summary>
        public static string BranchType {
            get {
                return ResourceManager.GetString("BranchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capital.
        /// </summary>
        public static string Capital {
            get {
                return ResourceManager.GetString("Capital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Type.
        /// </summary>
        public static string CarType {
            get {
                return ResourceManager.GetString("CarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Type List.
        /// </summary>
        public static string CarTypeList {
            get {
                return ResourceManager.GetString("CarTypeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Type Name.
        /// </summary>
        public static string CarTypeName {
            get {
                return ResourceManager.GetString("CarTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Id.
        /// </summary>
        public static string Cate_Id {
            get {
                return ResourceManager.GetString("Cate_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string Cate_Name {
            get {
                return ResourceManager.GetString("Cate_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD All Code List.
        /// </summary>
        public static string CDAllCodeList {
            get {
                return ResourceManager.GetString("CDAllCodeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD Name.
        /// </summary>
        public static string CDName {
            get {
                return ResourceManager.GetString("CDName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD Type.
        /// </summary>
        public static string CDType {
            get {
                return ResourceManager.GetString("CDType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD Val.
        /// </summary>
        public static string CDVal {
            get {
                return ResourceManager.GetString("CDVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person.
        /// </summary>
        public static string ContactPerson {
            get {
                return ResourceManager.GetString("ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Type.
        /// </summary>
        public static string DataType {
            get {
                return ResourceManager.GetString("DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dep.
        /// </summary>
        public static string Dep {
            get {
                return ResourceManager.GetString("Dep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Code.
        /// </summary>
        public static string Dep_Code {
            get {
                return ResourceManager.GetString("Dep_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Id.
        /// </summary>
        public static string Dep_Id {
            get {
                return ResourceManager.GetString("Dep_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Name.
        /// </summary>
        public static string Dep_Name {
            get {
                return ResourceManager.GetString("Dep_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Type ID.
        /// </summary>
        public static string DepartmentTypeID {
            get {
                return ResourceManager.GetString("DepartmentTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Type List.
        /// </summary>
        public static string DepartmentTypeList {
            get {
                return ResourceManager.GetString("DepartmentTypeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Type Name.
        /// </summary>
        public static string DepartmentTypeName {
            get {
                return ResourceManager.GetString("DepartmentTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISCIPLINES.
        /// </summary>
        public static string DISCIPLINES {
            get {
                return ResourceManager.GetString("DISCIPLINES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division Code.
        /// </summary>
        public static string Div_Code {
            get {
                return ResourceManager.GetString("Div_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division Id.
        /// </summary>
        public static string DivId {
            get {
                return ResourceManager.GetString("DivId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division Name.
        /// </summary>
        public static string DivName {
            get {
                return ResourceManager.GetString("DivName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emp Code.
        /// </summary>
        public static string EmpCode {
            get {
                return ResourceManager.GetString("EmpCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Infor.
        /// </summary>
        public static string EmployeeInfor {
            get {
                return ResourceManager.GetString("EmployeeInfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee List.
        /// </summary>
        public static string EmployeeList {
            get {
                return ResourceManager.GetString("EmployeeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emp Name.
        /// </summary>
        public static string EmpName {
            get {
                return ResourceManager.GetString("EmpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District Code Empty.
        /// </summary>
        public static string err_DIS_CODE {
            get {
                return ResourceManager.GetString("err_DIS_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District Name Empty.
        /// </summary>
        public static string err_DIS_NAME {
            get {
                return ResourceManager.GetString("err_DIS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District not choose.
        /// </summary>
        public static string err_DIS_NAME_not_Choose {
            get {
                return ResourceManager.GetString("err_DIS_NAME_not_Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nation Code Empty.
        /// </summary>
        public static string err_NAT_CODE {
            get {
                return ResourceManager.GetString("err_NAT_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nation Name Empty.
        /// </summary>
        public static string err_NAT_NAME {
            get {
                return ResourceManager.GetString("err_NAT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nation not choose.
        /// </summary>
        public static string err_NAT_NAME_not_Choose {
            get {
                return ResourceManager.GetString("err_NAT_NAME_not_Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province Code Empty.
        /// </summary>
        public static string err_PRO_CODE {
            get {
                return ResourceManager.GetString("err_PRO_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province Name Empty.
        /// </summary>
        public static string err_PRO_NAME {
            get {
                return ResourceManager.GetString("err_PRO_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province not choose.
        /// </summary>
        public static string err_PRO_NAME_not_Choose {
            get {
                return ResourceManager.GetString("err_PRO_NAME_not_Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ward Code Empty.
        /// </summary>
        public static string err_WAR_CODE {
            get {
                return ResourceManager.GetString("err_WAR_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ward Name Empty.
        /// </summary>
        public static string err_WAR_NAME {
            get {
                return ResourceManager.GetString("err_WAR_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exp Acctno.
        /// </summary>
        public static string Exp_Acctno {
            get {
                return ResourceManager.GetString("Exp_Acctno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exp Acctno.
        /// </summary>
        public static string ExpAcctno {
            get {
                return ResourceManager.GetString("ExpAcctno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father Id.
        /// </summary>
        public static string Father_Id {
            get {
                return ResourceManager.GetString("Father_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father Id.
        /// </summary>
        public static string FatherID {
            get {
                return ResourceManager.GetString("FatherID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goods Code.
        /// </summary>
        public static string Gd_Code {
            get {
                return ResourceManager.GetString("Gd_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goods Type Code.
        /// </summary>
        public static string Gd_Type_Code {
            get {
                return ResourceManager.GetString("Gd_Type_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goods Code.
        /// </summary>
        public static string GoodsCode {
            get {
                return ResourceManager.GetString("GoodsCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goods Id.
        /// </summary>
        public static string GoodsID {
            get {
                return ResourceManager.GetString("GoodsID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goods Name.
        /// </summary>
        public static string GoodsName {
            get {
                return ResourceManager.GetString("GoodsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoodsType Id.
        /// </summary>
        public static string GoodsTypeID {
            get {
                return ResourceManager.GetString("GoodsTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoodsType Name.
        /// </summary>
        public static string GoodsTypeName {
            get {
                return ResourceManager.GetString("GoodsTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Code.
        /// </summary>
        public static string Group_Code {
            get {
                return ResourceManager.GetString("Group_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Id.
        /// </summary>
        public static string Group_Id {
            get {
                return ResourceManager.GetString("Group_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Level.
        /// </summary>
        public static string Group_Level {
            get {
                return ResourceManager.GetString("Group_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        public static string Group_Name {
            get {
                return ResourceManager.GetString("Group_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Group.
        /// </summary>
        public static string GroupDep {
            get {
                return ResourceManager.GetString("GroupDep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Parent Name.
        /// </summary>
        public static string GroupParentName {
            get {
                return ResourceManager.GetString("GroupParentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inc Acctno.
        /// </summary>
        public static string IncAcctno {
            get {
                return ResourceManager.GetString("IncAcctno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insuare Company Name.
        /// </summary>
        public static string InsuareCompanyName {
            get {
                return ResourceManager.GetString("InsuareCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insure Company ID.
        /// </summary>
        public static string InsureCompanyID {
            get {
                return ResourceManager.GetString("InsureCompanyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insure Company List.
        /// </summary>
        public static string InsureCompanyList {
            get {
                return ResourceManager.GetString("InsureCompanyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Leaf.
        /// </summary>
        public static string Is_Leaf {
            get {
                return ResourceManager.GetString("Is_Leaf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        public static string lbl_wg_District {
            get {
                return ResourceManager.GetString("lbl_wg_District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District Code.
        /// </summary>
        public static string lbl_wg_District_Code {
            get {
                return ResourceManager.GetString("lbl_wg_District_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District Name.
        /// </summary>
        public static string lbl_wg_District_Name {
            get {
                return ResourceManager.GetString("lbl_wg_District_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District Type.
        /// </summary>
        public static string lbl_wg_District_Type {
            get {
                return ResourceManager.GetString("lbl_wg_District_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nation.
        /// </summary>
        public static string lbl_wg_Nation {
            get {
                return ResourceManager.GetString("lbl_wg_Nation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nation Code.
        /// </summary>
        public static string lbl_wg_Nation_Code {
            get {
                return ResourceManager.GetString("lbl_wg_Nation_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nation Name.
        /// </summary>
        public static string lbl_wg_Nation_Name {
            get {
                return ResourceManager.GetString("lbl_wg_Nation_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        public static string lbl_wg_Province {
            get {
                return ResourceManager.GetString("lbl_wg_Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province Code.
        /// </summary>
        public static string lbl_wg_Province_Code {
            get {
                return ResourceManager.GetString("lbl_wg_Province_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province Name.
        /// </summary>
        public static string lbl_wg_Province_Name {
            get {
                return ResourceManager.GetString("lbl_wg_Province_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province Type.
        /// </summary>
        public static string lbl_wg_Province_Type {
            get {
                return ResourceManager.GetString("lbl_wg_Province_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ward.
        /// </summary>
        public static string lbl_wg_Ward {
            get {
                return ResourceManager.GetString("lbl_wg_Ward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ward Code.
        /// </summary>
        public static string lbl_wg_Ward_Code {
            get {
                return ResourceManager.GetString("lbl_wg_Ward_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ward Name.
        /// </summary>
        public static string lbl_wg_Ward_Name {
            get {
                return ResourceManager.GetString("lbl_wg_Ward_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ward Type.
        /// </summary>
        public static string lbl_wg_Ward_Type {
            get {
                return ResourceManager.GetString("lbl_wg_Ward_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument List.
        /// </summary>
        public static string lblArgument {
            get {
                return ResourceManager.GetString("lblArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Category List.
        /// </summary>
        public static string lblAssetCategory {
            get {
                return ResourceManager.GetString("lblAssetCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Group List.
        /// </summary>
        public static string lblAssetGroup {
            get {
                return ResourceManager.GetString("lblAssetGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Type List.
        /// </summary>
        public static string lblAssetType {
            get {
                return ResourceManager.GetString("lblAssetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch list.
        /// </summary>
        public static string lblBranch {
            get {
                return ResourceManager.GetString("lblBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string lblBranch1 {
            get {
                return ResourceManager.GetString("lblBranch1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department List.
        /// </summary>
        public static string lblDepartment {
            get {
                return ResourceManager.GetString("lblDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division List.
        /// </summary>
        public static string lblDivision {
            get {
                return ResourceManager.GetString("lblDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File export name.
        /// </summary>
        public static string lblFileExportName {
            get {
                return ResourceManager.GetString("lblFileExportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goods.
        /// </summary>
        public static string lblGoods {
            get {
                return ResourceManager.GetString("lblGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoodsType.
        /// </summary>
        public static string lblGoodsType {
            get {
                return ResourceManager.GetString("lblGoodsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headquarter.
        /// </summary>
        public static string lblHeadquarter {
            get {
                return ResourceManager.GetString("lblHeadquarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string lblRegion {
            get {
                return ResourceManager.GetString("lblRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regions list.
        /// </summary>
        public static string lblRegions {
            get {
                return ResourceManager.GetString("lblRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string lblSupplier {
            get {
                return ResourceManager.GetString("lblSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupplierType.
        /// </summary>
        public static string lblSupplierType {
            get {
                return ResourceManager.GetString("lblSupplierType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction office.
        /// </summary>
        public static string lblTransactionOffice {
            get {
                return ResourceManager.GetString("lblTransactionOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licene.
        /// </summary>
        public static string Licene {
            get {
                return ResourceManager.GetString("Licene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liq Acctno.
        /// </summary>
        public static string LiqAcctno {
            get {
                return ResourceManager.GetString("LiqAcctno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSTODR.
        /// </summary>
        public static string LSTODR {
            get {
                return ResourceManager.GetString("LSTODR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        public static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Time.
        /// </summary>
        public static string Max_Time {
            get {
                return ResourceManager.GetString("Max_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model List.
        /// </summary>
        public static string ModelList {
            get {
                return ResourceManager.GetString("ModelList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Name.
        /// </summary>
        public static string ModelName {
            get {
                return ResourceManager.GetString("ModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset not use.
        /// </summary>
        public static string NotYesUse {
            get {
                return ResourceManager.GetString("NotYesUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent ID.
        /// </summary>
        public static string Parent_Id {
            get {
                return ResourceManager.GetString("Parent_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Rate.
        /// </summary>
        public static string PowerRate {
            get {
                return ResourceManager.GetString("PowerRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranked.
        /// </summary>
        public static string Ranked {
            get {
                return ResourceManager.GetString("Ranked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Status.
        /// </summary>
        public static string Record_Status {
            get {
                return ResourceManager.GetString("Record_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Status.
        /// </summary>
        public static string RecordStatus {
            get {
                return ResourceManager.GetString("RecordStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region Code.
        /// </summary>
        public static string Region_Code {
            get {
                return ResourceManager.GetString("Region_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region Id.
        /// </summary>
        public static string RegionID {
            get {
                return ResourceManager.GetString("RegionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region Name.
        /// </summary>
        public static string RegionName {
            get {
                return ResourceManager.GetString("RegionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Code.
        /// </summary>
        public static string Sup_Code {
            get {
                return ResourceManager.GetString("Sup_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Type Code.
        /// </summary>
        public static string Sup_Type_Code {
            get {
                return ResourceManager.GetString("Sup_Type_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sup ID.
        /// </summary>
        public static string SupID {
            get {
                return ResourceManager.GetString("SupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sup Name.
        /// </summary>
        public static string SupName {
            get {
                return ResourceManager.GetString("SupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupType ID.
        /// </summary>
        public static string SupTypeID {
            get {
                return ResourceManager.GetString("SupTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupType Name.
        /// </summary>
        public static string SupTypeName {
            get {
                return ResourceManager.GetString("SupTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax No.
        /// </summary>
        public static string TaxNo {
            get {
                return ResourceManager.GetString("TaxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel.
        /// </summary>
        public static string Tel {
            get {
                return ResourceManager.GetString("Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Code.
        /// </summary>
        public static string Type_Code {
            get {
                return ResourceManager.GetString("Type_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Id.
        /// </summary>
        public static string Type_Id {
            get {
                return ResourceManager.GetString("Type_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Name.
        /// </summary>
        public static string Type_Name {
            get {
                return ResourceManager.GetString("Type_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Shortcut.
        /// </summary>
        public static string Type_Shortcut {
            get {
                return ResourceManager.GetString("Type_Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit ID.
        /// </summary>
        public static string UnitID {
            get {
                return ResourceManager.GetString("UnitID", resourceCulture);
            }
        }
    }
}
