//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gMVVM.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public CommonResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gMVVM.Resources.CommonResource", typeof(CommonResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach date.
        /// </summary>
        public static string ATTACH_DT {
            get {
                return ResourceManager.GetString("ATTACH_DT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auth status.
        /// </summary>
        public static string AUTH_STATUS {
            get {
                return ResourceManager.GetString("AUTH_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string btnApprove {
            get {
                return ResourceManager.GetString("btnApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string btnBack {
            get {
                return ResourceManager.GetString("btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string btnClose {
            get {
                return ResourceManager.GetString("btnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string btnDelete {
            get {
                return ResourceManager.GetString("btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect All.
        /// </summary>
        public static string btnDeselectAll {
            get {
                return ResourceManager.GetString("btnDeselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string btnEdit {
            get {
                return ResourceManager.GetString("btnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string btnInsert {
            get {
                return ResourceManager.GetString("btnInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string btnOk {
            get {
                return ResourceManager.GetString("btnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string btnSelectAll {
            get {
                return ResourceManager.GetString("btnSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send plan.
        /// </summary>
        public static string btnSendPlan {
            get {
                return ResourceManager.GetString("btnSendPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string btnUpdate {
            get {
                return ResourceManager.GetString("btnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View detail.
        /// </summary>
        public static string btnView {
            get {
                return ResourceManager.GetString("btnView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD.
        /// </summary>
        public static string CD {
            get {
                return ResourceManager.GetString("CD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DT.
        /// </summary>
        public static string DT {
            get {
                return ResourceManager.GetString("DT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee id.
        /// </summary>
        public static string EMP_ID {
            get {
                return ResourceManager.GetString("EMP_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting failed. This item was approved..
        /// </summary>
        public static string errorApproveAlready {
            get {
                return ResourceManager.GetString("errorApproveAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not connect server.
        /// </summary>
        public static string errorCannotConnectServer {
            get {
                return ResourceManager.GetString("errorCannotConnectServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to close customer accounts, so existing account balances.
        /// </summary>
        public static string errorClosedStatus {
            get {
                return ResourceManager.GetString("errorClosedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete false. Please check your permission or object is using!.
        /// </summary>
        public static string errorDelete {
            get {
                return ResourceManager.GetString("errorDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value&apos;s not empty.
        /// </summary>
        public static string errorEmpty {
            get {
                return ResourceManager.GetString("errorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False. Existed item!.
        /// </summary>
        public static string errorExist {
            get {
                return ResourceManager.GetString("errorExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert false. Please check your input value!.
        /// </summary>
        public static string errorInsert {
            get {
                return ResourceManager.GetString("errorInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update false. Please check your input value!.
        /// </summary>
        public static string errorUpdate {
            get {
                return ResourceManager.GetString("errorUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item was existed!.
        /// </summary>
        public static string Existed {
            get {
                return ResourceManager.GetString("Existed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        public static string FILE_NAME_OLD {
            get {
                return ResourceManager.GetString("FILE_NAME_OLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size.
        /// </summary>
        public static string FILE_SIZE {
            get {
                return ResourceManager.GetString("FILE_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is single data.
        /// </summary>
        public static string IsSingle {
            get {
                return ResourceManager.GetString("IsSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Update.
        /// </summary>
        public static string lbIsUpdate {
            get {
                return ResourceManager.GetString("lbIsUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---All---.
        /// </summary>
        public static string lblAll {
            get {
                return ResourceManager.GetString("lblAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string lblApprove {
            get {
                return ResourceManager.GetString("lblApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string lblApproved {
            get {
                return ResourceManager.GetString("lblApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string lblChangePass {
            get {
                return ResourceManager.GetString("lblChangePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string lblClose {
            get {
                return ResourceManager.GetString("lblClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string lblCommon {
            get {
                return ResourceManager.GetString("lblCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string lblDetail {
            get {
                return ResourceManager.GetString("lblDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disapproved.
        /// </summary>
        public static string lblDisApprove {
            get {
                return ResourceManager.GetString("lblDisApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string lblDoUpdate {
            get {
                return ResourceManager.GetString("lblDoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string lblEdit {
            get {
                return ResourceManager.GetString("lblEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        public static string lblFalse {
            get {
                return ResourceManager.GetString("lblFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File attach detail.
        /// </summary>
        public static string lblFileDetail {
            get {
                return ResourceManager.GetString("lblFileDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string lblHello {
            get {
                return ResourceManager.GetString("lblHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string lblHome {
            get {
                return ResourceManager.GetString("lblHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string lblID {
            get {
                return ResourceManager.GetString("lblID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrastructure.
        /// </summary>
        public static string lblInfrastructure {
            get {
                return ResourceManager.GetString("lblInfrastructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string lblInsert {
            get {
                return ResourceManager.GetString("lblInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item is being used.
        /// </summary>
        public static string lblIsUsing {
            get {
                return ResourceManager.GetString("lblIsUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string lblLogout {
            get {
                return ResourceManager.GetString("lblLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not update.
        /// </summary>
        public static string lblNotUpdate {
            get {
                return ResourceManager.GetString("lblNotUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string lblReport {
            get {
                return ResourceManager.GetString("lblReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string lblSearch {
            get {
                return ResourceManager.GetString("lblSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string lblSystemRole {
            get {
                return ResourceManager.GetString("lblSystemRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logined from.
        /// </summary>
        public static string lblTimeLogin {
            get {
                return ResourceManager.GetString("lblTimeLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View profile.
        /// </summary>
        public static string lblViewProfile {
            get {
                return ResourceManager.GetString("lblViewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please waiting....
        /// </summary>
        public static string lblWaiting {
            get {
                return ResourceManager.GetString("lblWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Update.
        /// </summary>
        public static string lbNotUpdate {
            get {
                return ResourceManager.GetString("lbNotUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File attach list.
        /// </summary>
        public static string LstFileAttach {
            get {
                return ResourceManager.GetString("LstFileAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete it?.
        /// </summary>
        public static string msgDelete {
            get {
                return ResourceManager.GetString("msgDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to unapprove it?.
        /// </summary>
        public static string msgSendBack {
            get {
                return ResourceManager.GetString("msgSendBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to send it?.
        /// </summary>
        public static string msgSendplan {
            get {
                return ResourceManager.GetString("msgSendplan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfull!.
        /// </summary>
        public static string msgSuccessful {
            get {
                return ResourceManager.GetString("msgSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item has not existed.
        /// </summary>
        public static string NotExisted {
            get {
                return ResourceManager.GetString("NotExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string PATH_OLD {
            get {
                return ResourceManager.GetString("PATH_OLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string STATUS {
            get {
                return ResourceManager.GetString("STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
