//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gMVVM.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PlanManagerResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public PlanManagerResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gMVVM.Resources.PlanManagerResource", typeof(PlanManagerResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amort end date.
        /// </summary>
        public static string Amort_End_DT {
            get {
                return ResourceManager.GetString("Amort_End_DT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amort firt date.
        /// </summary>
        public static string Amort_Firt_DT {
            get {
                return ResourceManager.GetString("Amort_Firt_DT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amort Rate.
        /// </summary>
        public static string AmortRate {
            get {
                return ResourceManager.GetString("AmortRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Exe.
        /// </summary>
        public static string AmountExe {
            get {
                return ResourceManager.GetString("AmountExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve Value.
        /// </summary>
        public static string ApproveValue {
            get {
                return ResourceManager.GetString("ApproveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Asset.
        /// </summary>
        public static string AssetGroup {
            get {
                return ResourceManager.GetString("AssetGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Id.
        /// </summary>
        public static string AssetID {
            get {
                return ResourceManager.GetString("AssetID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Name.
        /// </summary>
        public static string AssetName {
            get {
                return ResourceManager.GetString("AssetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auth Status.
        /// </summary>
        public static string Auth_Status {
            get {
                return ResourceManager.GetString("Auth_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string BranchID {
            get {
                return ResourceManager.GetString("BranchID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BranchName.
        /// </summary>
        public static string BranchName {
            get {
                return ResourceManager.GetString("BranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add asset.
        /// </summary>
        public static string btnAddAsset {
            get {
                return ResourceManager.GetString("btnAddAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send back.
        /// </summary>
        public static string btnSendBack {
            get {
                return ResourceManager.GetString("btnSendBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send plan.
        /// </summary>
        public static string btnSendPlan {
            get {
                return ResourceManager.GetString("btnSendPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string Checked {
            get {
                return ResourceManager.GetString("Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction Type.
        /// </summary>
        public static string Const_Type {
            get {
                return ResourceManager.GetString("Const_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConstID.
        /// </summary>
        public static string ConstID {
            get {
                return ResourceManager.GetString("ConstID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConstName.
        /// </summary>
        public static string ConstName {
            get {
                return ResourceManager.GetString("ConstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction list.
        /// </summary>
        public static string ConstructionList {
            get {
                return ResourceManager.GetString("ConstructionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Construction/Repair.
        /// </summary>
        public static string ConstructionRepair {
            get {
                return ResourceManager.GetString("ConstructionRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current year.
        /// </summary>
        public static string CurrentYear {
            get {
                return ResourceManager.GetString("CurrentYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Div Id.
        /// </summary>
        public static string Div_Id {
            get {
                return ResourceManager.GetString("Div_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect Date.
        /// </summary>
        public static string EffectDate {
            get {
                return ResourceManager.GetString("EffectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndDate.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Exe.
        /// </summary>
        public static string ExeDate {
            get {
                return ResourceManager.GetString("ExeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Value.
        /// </summary>
        public static string ExpectedValue {
            get {
                return ResourceManager.GetString("ExpectedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goods Id.
        /// </summary>
        public static string GoodsID {
            get {
                return ResourceManager.GetString("GoodsID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goods Name.
        /// </summary>
        public static string GoodsName {
            get {
                return ResourceManager.GetString("GoodsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new construction.
        /// </summary>
        public static string lblAddConstruction {
            get {
                return ResourceManager.GetString("lblAddConstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIST OF BANK ASSETS.
        /// </summary>
        public static string lblAssetList {
            get {
                return ResourceManager.GetString("lblAssetList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction list.
        /// </summary>
        public static string lblConList {
            get {
                return ResourceManager.GetString("lblConList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSTRUCTION LIST.
        /// </summary>
        public static string lblConstList {
            get {
                return ResourceManager.GetString("lblConstList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction plan list.
        /// </summary>
        public static string lblConstruction {
            get {
                return ResourceManager.GetString("lblConstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total value worked.
        /// </summary>
        public static string lblDoneValue {
            get {
                return ResourceManager.GetString("lblDoneValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction detail.
        /// </summary>
        public static string lblEditConstruction {
            get {
                return ResourceManager.GetString("lblEditConstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of liquid asset.
        /// </summary>
        public static string lblLiquidAsset {
            get {
                return ResourceManager.GetString("lblLiquidAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liquidation plan list.
        /// </summary>
        public static string lblLiquidation {
            get {
                return ResourceManager.GetString("lblLiquidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIQUIDATION LIST.
        /// </summary>
        public static string lblLiquidList {
            get {
                return ResourceManager.GetString("lblLiquidList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent.
        /// </summary>
        public static string lblPer {
            get {
                return ResourceManager.GetString("lblPer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Name.
        /// </summary>
        public static string lblPlanBranch {
            get {
                return ResourceManager.GetString("lblPlanBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAN INFORMATION.
        /// </summary>
        public static string lblPlanInfo {
            get {
                return ResourceManager.GetString("lblPlanInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan list.
        /// </summary>
        public static string lblPlanList {
            get {
                return ResourceManager.GetString("lblPlanList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send plan is false.
        /// </summary>
        public static string lblSendPlanError {
            get {
                return ResourceManager.GetString("lblSendPlanError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send plan successful.
        /// </summary>
        public static string lblSendPlanSuccessfull {
            get {
                return ResourceManager.GetString("lblSendPlanSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string lblStepStatus {
            get {
                return ResourceManager.GetString("lblStepStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totality.
        /// </summary>
        public static string lblTotality {
            get {
                return ResourceManager.GetString("lblTotality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade plan list.
        /// </summary>
        public static string lblTrade {
            get {
                return ResourceManager.GetString("lblTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade detail.
        /// </summary>
        public static string lblTradeDetail {
            get {
                return ResourceManager.GetString("lblTradeDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade plan .
        /// </summary>
        public static string lblTradeEdit {
            get {
                return ResourceManager.GetString("lblTradeEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liquid Type.
        /// </summary>
        public static string LiquidType {
            get {
                return ResourceManager.GetString("LiquidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month Exe.
        /// </summary>
        public static string MonthExe {
            get {
                return ResourceManager.GetString("MonthExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month Liquid.
        /// </summary>
        public static string MonthLiquid {
            get {
                return ResourceManager.GetString("MonthLiquid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month of amort.
        /// </summary>
        public static string MonthOfAmort {
            get {
                return ResourceManager.GetString("MonthOfAmort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plans have been sent back.
        /// </summary>
        public static string msgSendBack {
            get {
                return ResourceManager.GetString("msgSendBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan sent successfully.
        /// </summary>
        public static string msgSendPlan {
            get {
                return ResourceManager.GetString("msgSendPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Id.
        /// </summary>
        public static string PlanID {
            get {
                return ResourceManager.GetString("PlanID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Month.
        /// </summary>
        public static string PlanMonth {
            get {
                return ResourceManager.GetString("PlanMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Name.
        /// </summary>
        public static string PlanName {
            get {
                return ResourceManager.GetString("PlanName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put into liquidation.
        /// </summary>
        public static string PutLiquid {
            get {
                return ResourceManager.GetString("PutLiquid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Exe.
        /// </summary>
        public static string QuantityExe {
            get {
                return ResourceManager.GetString("QuantityExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Remain.
        /// </summary>
        public static string QuantityRemain {
            get {
                return ResourceManager.GetString("QuantityRemain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Status.
        /// </summary>
        public static string Record_Status {
            get {
                return ResourceManager.GetString("Record_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Status.
        /// </summary>
        public static string RecordStatusAss {
            get {
                return ResourceManager.GetString("RecordStatusAss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery Value.
        /// </summary>
        public static string RecoveryValue {
            get {
                return ResourceManager.GetString("RecoveryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remain Amort.
        /// </summary>
        public static string RemainMonAmort {
            get {
                return ResourceManager.GetString("RemainMonAmort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemainValue.
        /// </summary>
        public static string RemainValue {
            get {
                return ResourceManager.GetString("RemainValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        public static string Row {
            get {
                return ResourceManager.GetString("Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartDate.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Amort.
        /// </summary>
        public static string StatusAmort {
            get {
                return ResourceManager.GetString("StatusAmort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Asset.
        /// </summary>
        public static string StatusAsset {
            get {
                return ResourceManager.GetString("StatusAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier ID.
        /// </summary>
        public static string SupplierID {
            get {
                return ResourceManager.GetString("SupplierID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Name.
        /// </summary>
        public static string SupplierName {
            get {
                return ResourceManager.GetString("SupplierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Name.
        /// </summary>
        public static string TradeName {
            get {
                return ResourceManager.GetString("TradeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Id.
        /// </summary>
        public static string UnitID {
            get {
                return ResourceManager.GetString("UnitID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used Amount.
        /// </summary>
        public static string UsedAmt {
            get {
                return ResourceManager.GetString("UsedAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Value.
        /// </summary>
        public static string VerifyValue {
            get {
                return ResourceManager.GetString("VerifyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verson.
        /// </summary>
        public static string Verson {
            get {
                return ResourceManager.GetString("Verson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year Exe.
        /// </summary>
        public static string YearExe {
            get {
                return ResourceManager.GetString("YearExe", resourceCulture);
            }
        }
    }
}
