//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gMVVM.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class QuanLySoThuResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public QuanLySoThuResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gMVVM.Resources.QuanLySoThuResource", typeof(QuanLySoThuResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string lblBaoCaoTonKho {
            get {
                return ResourceManager.GetString("lblBaoCaoTonKho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string lblDonViTinh {
            get {
                return ResourceManager.GetString("lblDonViTinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string lblGhiChu {
            get {
                return ResourceManager.GetString("lblGhiChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string lblMaLo {
            get {
                return ResourceManager.GetString("lblMaLo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vouchers ID.
        /// </summary>
        public static string lblMaPhieuNhap {
            get {
                return ResourceManager.GetString("lblMaPhieuNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine ID.
        /// </summary>
        public static string lblMaThuoc {
            get {
                return ResourceManager.GetString("lblMaThuoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string lblMoTa {
            get {
                return ResourceManager.GetString("lblMoTa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired date.
        /// </summary>
        public static string lblNgayHethang {
            get {
                return ResourceManager.GetString("lblNgayHethang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase date.
        /// </summary>
        public static string lblNgayNhap {
            get {
                return ResourceManager.GetString("lblNgayNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produce date.
        /// </summary>
        public static string lblNgaySanXuat {
            get {
                return ResourceManager.GetString("lblNgaySanXuat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase number.
        /// </summary>
        public static string lblNhapThem {
            get {
                return ResourceManager.GetString("lblNhapThem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch number.
        /// </summary>
        public static string lblSoLo {
            get {
                return ResourceManager.GetString("lblSoLo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine batch number.
        /// </summary>
        public static string lblSoLoThuoc {
            get {
                return ResourceManager.GetString("lblSoLoThuoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string lblSoLuong {
            get {
                return ResourceManager.GetString("lblSoLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine Name.
        /// </summary>
        public static string lblTenThuoc {
            get {
                return ResourceManager.GetString("lblTenThuoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string lblTinhTrang {
            get {
                return ResourceManager.GetString("lblTinhTrang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum.
        /// </summary>
        public static string lblToiThieu {
            get {
                return ResourceManager.GetString("lblToiThieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string lblTonKho {
            get {
                return ResourceManager.GetString("lblTonKho", resourceCulture);
            }
        }
    }
}
