//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gMVVM.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SearchResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public SearchResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gMVVM.Resources.SearchResource", typeof(SearchResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string Checked {
            get {
                return ResourceManager.GetString("Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string lblAddr {
            get {
                return ResourceManager.GetString("lblAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Searching.
        /// </summary>
        public static string lblAssetSearching {
            get {
                return ResourceManager.GetString("lblAssetSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lblBidCostract.
        /// </summary>
        public static string lblBidCostract {
            get {
                return ResourceManager.GetString("lblBidCostract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid Searching.
        /// </summary>
        public static string lblBidSearching {
            get {
                return ResourceManager.GetString("lblBidSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Id.
        /// </summary>
        public static string lblBranchID {
            get {
                return ResourceManager.GetString("lblBranchID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Information.
        /// </summary>
        public static string lblBranchInformation {
            get {
                return ResourceManager.GetString("lblBranchInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch searching.
        /// </summary>
        public static string lblBranchSearching {
            get {
                return ResourceManager.GetString("lblBranchSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Searching.
        /// </summary>
        public static string lblCarSearching {
            get {
                return ResourceManager.GetString("lblCarSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConBid Searching.
        /// </summary>
        public static string lblConBidSearching {
            get {
                return ResourceManager.GetString("lblConBidSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Information.
        /// </summary>
        public static string lblContractInformation {
            get {
                return ResourceManager.GetString("lblContractInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Searching.
        /// </summary>
        public static string lblContractSearching {
            get {
                return ResourceManager.GetString("lblContractSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department searching.
        /// </summary>
        public static string lblDepartmentSearching {
            get {
                return ResourceManager.GetString("lblDepartmentSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division Id.
        /// </summary>
        public static string lblDivID {
            get {
                return ResourceManager.GetString("lblDivID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division Information.
        /// </summary>
        public static string lblDivisionInformation {
            get {
                return ResourceManager.GetString("lblDivisionInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division Searching.
        /// </summary>
        public static string lblDivisionSearching {
            get {
                return ResourceManager.GetString("lblDivisionSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division Name.
        /// </summary>
        public static string lblDivName {
            get {
                return ResourceManager.GetString("lblDivName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee&apos;s name.
        /// </summary>
        public static string lblEmployeeName {
            get {
                return ResourceManager.GetString("lblEmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee searching.
        /// </summary>
        public static string lblEmployeeSearching {
            get {
                return ResourceManager.GetString("lblEmployeeSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Asset Searching.
        /// </summary>
        public static string lblGroupAssetSearching {
            get {
                return ResourceManager.GetString("lblGroupAssetSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of employee.
        /// </summary>
        public static string lblListofEmployee {
            get {
                return ResourceManager.GetString("lblListofEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nation .
        /// </summary>
        public static string lblNationSearching {
            get {
                return ResourceManager.GetString("lblNationSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nation Code.
        /// </summary>
        public static string lblNationSearchingCode {
            get {
                return ResourceManager.GetString("lblNationSearchingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nation Name.
        /// </summary>
        public static string lblNationSearchingName {
            get {
                return ResourceManager.GetString("lblNationSearchingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string lblNotes {
            get {
                return ResourceManager.GetString("lblNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lblOfferPerson.
        /// </summary>
        public static string lblOfferPerson {
            get {
                return ResourceManager.GetString("lblOfferPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Searching.
        /// </summary>
        public static string lblPlanSearching {
            get {
                return ResourceManager.GetString("lblPlanSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search PO.
        /// </summary>
        public static string lblPOSearching {
            get {
                return ResourceManager.GetString("lblPOSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lblProfileConstract.
        /// </summary>
        public static string lblProfileConstract {
            get {
                return ResourceManager.GetString("lblProfileConstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RetMaster Searching.
        /// </summary>
        public static string lblRetSearching {
            get {
                return ResourceManager.GetString("lblRetSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Searching.
        /// </summary>
        public static string lblSupplierSearching {
            get {
                return ResourceManager.GetString("lblSupplierSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User searching.
        /// </summary>
        public static string lblUserSearching {
            get {
                return ResourceManager.GetString("lblUserSearching", resourceCulture);
            }
        }
    }
}
