//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gMVVM.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SystemRoleResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public SystemRoleResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gMVVM.Resources.SystemRoleResource", typeof(SystemRoleResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string ADDRESS {
            get {
                return ResourceManager.GetString("ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrastructure.
        /// </summary>
        public static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string btnOk {
            get {
                return ResourceManager.GetString("btnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string btnSend {
            get {
                return ResourceManager.GetString("btnSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer?.
        /// </summary>
        public static string DEALER {
            get {
                return ResourceManager.GetString("DEALER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EMAIL {
            get {
                return ResourceManager.GetString("EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not Exist in DC system..
        /// </summary>
        public static string ExistUser {
            get {
                return ResourceManager.GetString("ExistUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group user id.
        /// </summary>
        public static string GRPID {
            get {
                return ResourceManager.GetString("GRPID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name.
        /// </summary>
        public static string GRPNAME {
            get {
                return ResourceManager.GetString("GRPNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERP MANAGEMENT.
        /// </summary>
        public static string lblAsset {
            get {
                return ResourceManager.GetString("lblAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From file.
        /// </summary>
        public static string lblAuto {
            get {
                return ResourceManager.GetString("lblAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bach Viet College.
        /// </summary>
        public static string lblBachViet {
            get {
                return ResourceManager.GetString("lblBachViet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        public static string lblBack {
            get {
                return ResourceManager.GetString("lblBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string lblChangePass {
            get {
                return ResourceManager.GetString("lblChangePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string lblClass {
            get {
                return ResourceManager.GetString("lblClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security code.
        /// </summary>
        public static string lblCode {
            get {
                return ResourceManager.GetString("lblCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string lblCust {
            get {
                return ResourceManager.GetString("lblCust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string lblDate {
            get {
                return ResourceManager.GetString("lblDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string lblDoSome {
            get {
                return ResourceManager.GetString("lblDoSome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string lblEnglish {
            get {
                return ResourceManager.GetString("lblEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file.
        /// </summary>
        public static string lblFile {
            get {
                return ResourceManager.GetString("lblFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, change your password on first time login.
        /// </summary>
        public static string lblFirsTime {
            get {
                return ResourceManager.GetString("lblFirsTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password.
        /// </summary>
        public static string lblForgotPassword {
            get {
                return ResourceManager.GetString("lblForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string lblFullName {
            get {
                return ResourceManager.GetString("lblFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group information.
        /// </summary>
        public static string lblGroup {
            get {
                return ResourceManager.GetString("lblGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BANKING EDUCATION SYSTEM.
        /// </summary>
        public static string lblHeader {
            get {
                return ResourceManager.GetString("lblHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is approve.
        /// </summary>
        public static string lblIsApprove {
            get {
                return ResourceManager.GetString("lblIsApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string lblLanguage {
            get {
                return ResourceManager.GetString("lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login System.
        /// </summary>
        public static string lblLogin {
            get {
                return ResourceManager.GetString("lblLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login false, Please check information again !.
        /// </summary>
        public static string lblLoginError {
            get {
                return ResourceManager.GetString("lblLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login System.
        /// </summary>
        public static string lblLoginTitle {
            get {
                return ResourceManager.GetString("lblLoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu information.
        /// </summary>
        public static string lblMenu {
            get {
                return ResourceManager.GetString("lblMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string lblNewPass {
            get {
                return ResourceManager.GetString("lblNewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password againt.
        /// </summary>
        public static string lblNewPassAgaint {
            get {
                return ResourceManager.GetString("lblNewPassAgaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name is not existed.
        /// </summary>
        public static string lblNotExist {
            get {
                return ResourceManager.GetString("lblNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is not match.
        /// </summary>
        public static string lblNotMatch {
            get {
                return ResourceManager.GetString("lblNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Password.
        /// </summary>
        public static string lblRenewPass {
            get {
                return ResourceManager.GetString("lblRenewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string lblRole {
            get {
                return ResourceManager.GetString("lblRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions role.
        /// </summary>
        public static string lblRoleAction {
            get {
                return ResourceManager.GetString("lblRoleAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu role.
        /// </summary>
        public static string lblRoleMenu {
            get {
                return ResourceManager.GetString("lblRoleMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles system.
        /// </summary>
        public static string lblRoles {
            get {
                return ResourceManager.GetString("lblRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security code.
        /// </summary>
        public static string lblSecurityCode {
            get {
                return ResourceManager.GetString("lblSecurityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, check your email to get security code.
        /// </summary>
        public static string lblSendSuccessful {
            get {
                return ResourceManager.GetString("lblSendSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubBranch.
        /// </summary>
        public static string lblSUBBR {
            get {
                return ResourceManager.GetString("lblSUBBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubBranch ID.
        /// </summary>
        public static string lblSUBBRID {
            get {
                return ResourceManager.GetString("lblSUBBRID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System manager.
        /// </summary>
        public static string lblSystemRole {
            get {
                return ResourceManager.GetString("lblSystemRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullName.
        /// </summary>
        public static string lblTlFullName {
            get {
                return ResourceManager.GetString("lblTlFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string lblUnit {
            get {
                return ResourceManager.GetString("lblUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Information.
        /// </summary>
        public static string lblUser {
            get {
                return ResourceManager.GetString("lblUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string lblUserID {
            get {
                return ResourceManager.GetString("lblUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string lblUsername {
            get {
                return ResourceManager.GetString("lblUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnamese.
        /// </summary>
        public static string lblVietnamese {
            get {
                return ResourceManager.GetString("lblVietnamese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu id.
        /// </summary>
        public static string MENU_ID {
            get {
                return ResourceManager.GetString("MENU_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string MENU_LINK {
            get {
                return ResourceManager.GetString("MENU_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu name.
        /// </summary>
        public static string MENU_NAME {
            get {
                return ResourceManager.GetString("MENU_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English name.
        /// </summary>
        public static string MENU_NAME_EL {
            get {
                return ResourceManager.GetString("MENU_NAME_EL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string MENU_ORDER {
            get {
                return ResourceManager.GetString("MENU_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu parent.
        /// </summary>
        public static string MENU_PARENT {
            get {
                return ResourceManager.GetString("MENU_PARENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string PHONE {
            get {
                return ResourceManager.GetString("PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string rdbChangePass {
            get {
                return ResourceManager.GetString("rdbChangePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get code.
        /// </summary>
        public static string rdbGetCode {
            get {
                return ResourceManager.GetString("rdbGetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role description.
        /// </summary>
        public static string ROLE_DESC {
            get {
                return ResourceManager.GetString("ROLE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name.
        /// </summary>
        public static string ROLE_ID {
            get {
                return ResourceManager.GetString("ROLE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Id.
        /// </summary>
        public static string SYSGRP_ID {
            get {
                return ResourceManager.GetString("SYSGRP_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        public static string SYSGRP_NAME {
            get {
                return ResourceManager.GetString("SYSGRP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashier.
        /// </summary>
        public static string TLCASH {
            get {
                return ResourceManager.GetString("TLCASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chief cash?.
        /// </summary>
        public static string TLCHIEFCASH {
            get {
                return ResourceManager.GetString("TLCHIEFCASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxCash.
        /// </summary>
        public static string TLCSHMAX {
            get {
                return ResourceManager.GetString("TLCSHMAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinCash.
        /// </summary>
        public static string TLCSMMIN {
            get {
                return ResourceManager.GetString("TLCSMMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string TLFullName {
            get {
                return ResourceManager.GetString("TLFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string TLGROUP {
            get {
                return ResourceManager.GetString("TLGROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User id.
        /// </summary>
        public static string TLID {
            get {
                return ResourceManager.GetString("TLID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string TLLEV {
            get {
                return ResourceManager.GetString("TLLEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string TLNANME {
            get {
                return ResourceManager.GetString("TLNANME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Officer?.
        /// </summary>
        public static string TLOFFICER {
            get {
                return ResourceManager.GetString("TLOFFICER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubBranch id.
        /// </summary>
        public static string TLSUBBRID {
            get {
                return ResourceManager.GetString("TLSUBBRID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string TLSYSGROUP {
            get {
                return ResourceManager.GetString("TLSYSGROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title .
        /// </summary>
        public static string TLTITLE {
            get {
                return ResourceManager.GetString("TLTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Group.
        /// </summary>
        public static string UserGroup {
            get {
                return ResourceManager.GetString("UserGroup", resourceCulture);
            }
        }
    }
}
