//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gMVVM.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidatorResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ValidatorResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gMVVM.Resources.ValidatorResource", typeof(ValidatorResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to character.
        /// </summary>
        public static string Character {
            get {
                return ResourceManager.GetString("Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to characters.
        /// </summary>
        public static string Characters {
            get {
                return ResourceManager.GetString("Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close till successful.
        /// </summary>
        public static string CloseTillSuccessful {
            get {
                return ResourceManager.GetString("CloseTillSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Disbursement Amount &lt;= Current Amount.
        /// </summary>
        public static string CompareAMTDB {
            get {
                return ResourceManager.GetString("CompareAMTDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current date.
        /// </summary>
        public static string CurrentDate {
            get {
                return ResourceManager.GetString("CurrentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete successful.
        /// </summary>
        public static string DeleteSuccessful {
            get {
                return ResourceManager.GetString("DeleteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete file successfull.
        /// </summary>
        public static string delFileSuccessful {
            get {
                return ResourceManager.GetString("delFileSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input incorrect.
        /// </summary>
        public static string ErroDecreaseValueCollateral {
            get {
                return ResourceManager.GetString("ErroDecreaseValueCollateral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete file fail.
        /// </summary>
        public static string errodelFileSuccessful {
            get {
                return ResourceManager.GetString("errodelFileSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input incorrect.
        /// </summary>
        public static string ErroIncreaseValueCollateral {
            get {
                return ResourceManager.GetString("ErroIncreaseValueCollateral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input incorrect.
        /// </summary>
        public static string ErroInput {
            get {
                return ResourceManager.GetString("ErroInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, check account id againt!.
        /// </summary>
        public static string ErrorAccDD {
            get {
                return ResourceManager.GetString("ErrorAccDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve false.
        /// </summary>
        public static string ErrorApprove {
            get {
                return ResourceManager.GetString("ErrorApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close fail.
        /// </summary>
        public static string ErrorClose {
            get {
                return ResourceManager.GetString("ErrorClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting fail: Denom&apos;s balance is greater than 0..
        /// </summary>
        public static string ErrorDeleteDenom {
            get {
                return ResourceManager.GetString("ErrorDeleteDenom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting fail: Till&apos;s balance is greater than 0..
        /// </summary>
        public static string ErrorDeleteTill {
            get {
                return ResourceManager.GetString("ErrorDeleteTill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert false, item was existed!.
        /// </summary>
        public static string ErrorExist {
            get {
                return ResourceManager.GetString("ErrorExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format is not correct.
        /// </summary>
        public static string ErrorFormat {
            get {
                return ResourceManager.GetString("ErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is full.
        /// </summary>
        public static string ErrorFull {
            get {
                return ResourceManager.GetString("ErrorFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert false. Please check your input value!.
        /// </summary>
        public static string ErrorInsert {
            get {
                return ResourceManager.GetString("ErrorInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not permission to use.
        /// </summary>
        public static string ErrorNotUse {
            get {
                return ResourceManager.GetString("ErrorNotUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update false. Please check your input value!.
        /// </summary>
        public static string ErrorUpdate {
            get {
                return ResourceManager.GetString("ErrorUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Till is opened.
        /// </summary>
        public static string ExistTill {
            get {
                return ResourceManager.GetString("ExistTill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You opened till ( Please. Login again!).
        /// </summary>
        public static string ExistUser {
            get {
                return ResourceManager.GetString("ExistUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullRelease.
        /// </summary>
        public static string FullRelease {
            get {
                return ResourceManager.GetString("FullRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert successful.
        /// </summary>
        public static string InsertSuccessful {
            get {
                return ResourceManager.GetString("InsertSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account was closed.
        /// </summary>
        public static string lblAccClosed {
            get {
                return ResourceManager.GetString("lblAccClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account is not of.
        /// </summary>
        public static string lblAccNotOwn {
            get {
                return ResourceManager.GetString("lblAccNotOwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve successful.
        /// </summary>
        public static string lblApproveSuccessfull {
            get {
                return ResourceManager.GetString("lblApproveSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve false.
        /// </summary>
        public static string lblAuthTransfeMoneyErro {
            get {
                return ResourceManager.GetString("lblAuthTransfeMoneyErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve successful.
        /// </summary>
        public static string lblAuthTransfeMoneySuccessful {
            get {
                return ResourceManager.GetString("lblAuthTransfeMoneySuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current year.
        /// </summary>
        public static string lblCurrentYear {
            get {
                return ResourceManager.GetString("lblCurrentYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due date &gt; current date.
        /// </summary>
        public static string lblDuedate {
            get {
                return ResourceManager.GetString("lblDuedate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Input amount &gt;= Current Amount in limit.
        /// </summary>
        public static string lblErroInCollateral {
            get {
                return ResourceManager.GetString("lblErroInCollateral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of limit is not enough.
        /// </summary>
        public static string lblErrorAmount {
            get {
                return ResourceManager.GetString("lblErrorAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error change your password.
        /// </summary>
        public static string lblErrorChange {
            get {
                return ResourceManager.GetString("lblErrorChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to delete this object.
        /// </summary>
        public static string lblErrorDeletePer {
            get {
                return ResourceManager.GetString("lblErrorDeletePer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday&lt; curent date.
        /// </summary>
        public static string lblErrorDOB {
            get {
                return ResourceManager.GetString("lblErrorDOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input amount is false.
        /// </summary>
        public static string lblErrorInput {
            get {
                return ResourceManager.GetString("lblErrorInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue date &lt;= current date.
        /// </summary>
        public static string lblErrorLicdate {
            get {
                return ResourceManager.GetString("lblErrorLicdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer amount is not match.
        /// </summary>
        public static string lblErrorMatchTransfer {
            get {
                return ResourceManager.GetString("lblErrorMatchTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not more than the first due date.
        /// </summary>
        public static string lblErrorMoreThan {
            get {
                return ResourceManager.GetString("lblErrorMoreThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule was be not really create.
        /// </summary>
        public static string lblErrorNotCrSch {
            get {
                return ResourceManager.GetString("lblErrorNotCrSch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output amount is false.
        /// </summary>
        public static string lblErrorOutput {
            get {
                return ResourceManager.GetString("lblErrorOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not permitted to approve this item.
        /// </summary>
        public static string lblErrorPermission {
            get {
                return ResourceManager.GetString("lblErrorPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select colleteral.
        /// </summary>
        public static string lblErrorSelectCol {
            get {
                return ResourceManager.GetString("lblErrorSelectCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select receive till.
        /// </summary>
        public static string lblErrorSelectTill {
            get {
                return ResourceManager.GetString("lblErrorSelectTill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of liquid asset error.
        /// </summary>
        public static string lblExistAssetLiquid {
            get {
                return ResourceManager.GetString("lblExistAssetLiquid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not the same.
        /// </summary>
        public static string lblExisted {
            get {
                return ResourceManager.GetString("lblExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account was fully disbursed.
        /// </summary>
        public static string lblFullAMT {
            get {
                return ResourceManager.GetString("lblFullAMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is using.
        /// </summary>
        public static string lblIsUsing {
            get {
                return ResourceManager.GetString("lblIsUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not less than.
        /// </summary>
        public static string lblLessThan {
            get {
                return ResourceManager.GetString("lblLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not more than.
        /// </summary>
        public static string lblMoreThan {
            get {
                return ResourceManager.GetString("lblMoreThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must.
        /// </summary>
        public static string lblMust {
            get {
                return ResourceManager.GetString("lblMust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account not approved or closed.
        /// </summary>
        public static string lblnotActive {
            get {
                return ResourceManager.GetString("lblnotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error not exist init accounting.
        /// </summary>
        public static string lblnotExist {
            get {
                return ResourceManager.GetString("lblnotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must open Till first.
        /// </summary>
        public static string lblNotOpenTill {
            get {
                return ResourceManager.GetString("lblNotOpenTill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to work!.
        /// </summary>
        public static string lblNotToWork {
            get {
                return ResourceManager.GetString("lblNotToWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not true.
        /// </summary>
        public static string lblNotTrue {
            get {
                return ResourceManager.GetString("lblNotTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment false.
        /// </summary>
        public static string lblPaymentErro {
            get {
                return ResourceManager.GetString("lblPaymentErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment successful.
        /// </summary>
        public static string lblPaymentSuccessful {
            get {
                return ResourceManager.GetString("lblPaymentSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to edit this object.
        /// </summary>
        public static string lblPerEdit {
            get {
                return ResourceManager.GetString("lblPerEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not permistion to view item.
        /// </summary>
        public static string lblPerView {
            get {
                return ResourceManager.GetString("lblPerView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to repeat.
        /// </summary>
        public static string lblRepeat {
            get {
                return ResourceManager.GetString("lblRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test row.
        /// </summary>
        public static string lblTestRow {
            get {
                return ResourceManager.GetString("lblTestRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to times.
        /// </summary>
        public static string lblTimes {
            get {
                return ResourceManager.GetString("lblTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to too large.
        /// </summary>
        public static string lblTooLarge {
            get {
                return ResourceManager.GetString("lblTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more than 0.
        /// </summary>
        public static string MoreZero {
            get {
                return ResourceManager.GetString("MoreZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must equal to.
        /// </summary>
        public static string MustEqual {
            get {
                return ResourceManager.GetString("MustEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must have.
        /// </summary>
        public static string MustHave {
            get {
                return ResourceManager.GetString("MustHave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not closed.
        /// </summary>
        public static string NotClosed {
            get {
                return ResourceManager.GetString("NotClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not empty.
        /// </summary>
        public static string NotEmpty {
            get {
                return ResourceManager.GetString("NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not exist.
        /// </summary>
        public static string NotExist {
            get {
                return ResourceManager.GetString("NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t opened till yet..
        /// </summary>
        public static string NotOpenTill {
            get {
                return ResourceManager.GetString("NotOpenTill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No update done and the actual date of actual completion.
        /// </summary>
        public static string NotYetUpdate {
            get {
                return ResourceManager.GetString("NotYetUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OfferStatus.
        /// </summary>
        public static string OfferStatus {
            get {
                return ResourceManager.GetString("OfferStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open till successfull.
        /// </summary>
        public static string OpenTillSuccessful {
            get {
                return ResourceManager.GetString("OpenTillSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARAMETERS Error.
        /// </summary>
        public static string PARAMETERSError {
            get {
                return ResourceManager.GetString("PARAMETERSError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send back error.
        /// </summary>
        public static string SendBackError {
            get {
                return ResourceManager.GetString("SendBackError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve successful.
        /// </summary>
        public static string SuccessfulApprove {
            get {
                return ResourceManager.GetString("SuccessfulApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close successful.
        /// </summary>
        public static string SuccessfulClose {
            get {
                return ResourceManager.GetString("SuccessfulClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send back successful.
        /// </summary>
        public static string SuccessfulSendBack {
            get {
                return ResourceManager.GetString("SuccessfulSendBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Till closed.
        /// </summary>
        public static string TillClosed {
            get {
                return ResourceManager.GetString("TillClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Till opened.
        /// </summary>
        public static string TillOpened {
            get {
                return ResourceManager.GetString("TillOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update successful.
        /// </summary>
        public static string UpdateSuccessful {
            get {
                return ResourceManager.GetString("UpdateSuccessful", resourceCulture);
            }
        }
    }
}
