#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gMVVM.Web.Services.KeHoach
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TAISANDAMBAO_PRO")]
	public partial class AssetDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCM_DOMAIN(CM_DOMAIN instance);
    partial void UpdateCM_DOMAIN(CM_DOMAIN instance);
    partial void DeleteCM_DOMAIN(CM_DOMAIN instance);
    #endregion
		
		public AssetDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["gMVVMConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AssetDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AssetDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AssetDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AssetDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CM_DOMAIN> CM_DOMAINs
		{
			get
			{
				return this.GetTable<CM_DOMAIN>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CM_DOMAIN_Ins")]
		public ISingleResult<CM_DOMAIN_InsResult> CM_DOMAIN_Ins([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_DOMAIN_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string p_DOMAIN_NAME, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string p_START_DATE, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string p_END_DATE, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(1000)")] string p_NOTES, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1)")] string p_RECORD_STATUS, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string p_MAKER_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string p_CREATE_DT, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string p_AUTH_STATUS, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string p_CHECKER_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string p_APPROVE_DT, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string p_EDIT_DATE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_DOMAIN_CODE, p_DOMAIN_NAME, p_START_DATE, p_END_DATE, p_NOTES, p_RECORD_STATUS, p_MAKER_ID, p_CREATE_DT, p_AUTH_STATUS, p_CHECKER_ID, p_APPROVE_DT, p_EDIT_DATE);
			return ((ISingleResult<CM_DOMAIN_InsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CM_DOMAIN_List")]
		public ISingleResult<CM_DOMAIN_ListResult> CM_DOMAIN_List()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<CM_DOMAIN_ListResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CM_DOMAIN_Search")]
		public ISingleResult<CM_DOMAIN_SearchResult> CM_DOMAIN_Search([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string p_DOMAIN_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string p_DOMAIN_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string p_DOMAIN_NAME, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string p_START_DATE, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string p_END_DATE, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(1000)")] string p_NOTES, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1)")] string p_RECORD_STATUS, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string p_MAKER_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string p_CREATE_DT, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string p_AUTH_STATUS, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string p_CHECKER_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string p_APPROVE_DT, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string p_EDIT_DATE, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_TOP)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_DOMAIN_ID, p_DOMAIN_CODE, p_DOMAIN_NAME, p_START_DATE, p_END_DATE, p_NOTES, p_RECORD_STATUS, p_MAKER_ID, p_CREATE_DT, p_AUTH_STATUS, p_CHECKER_ID, p_APPROVE_DT, p_EDIT_DATE, p_TOP);
			return ((ISingleResult<CM_DOMAIN_SearchResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CM_DOMAIN_Upd")]
		public ISingleResult<CM_DOMAIN_UpdResult> CM_DOMAIN_Upd([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string p_DOMAIN_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string p_DOMAIN_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string p_DOMAIN_NAME, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string p_START_DATE, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string p_END_DATE, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(1000)")] string p_NOTES, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1)")] string p_RECORD_STATUS, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string p_MAKER_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string p_CREATE_DT, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string p_AUTH_STATUS, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string p_CHECKER_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string p_APPROVE_DT, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string p_EDIT_DATE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_DOMAIN_ID, p_DOMAIN_CODE, p_DOMAIN_NAME, p_START_DATE, p_END_DATE, p_NOTES, p_RECORD_STATUS, p_MAKER_ID, p_CREATE_DT, p_AUTH_STATUS, p_CHECKER_ID, p_APPROVE_DT, p_EDIT_DATE);
			return ((ISingleResult<CM_DOMAIN_UpdResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CM_DOMAIN")]
	public partial class CM_DOMAIN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _DOMAIN_ID;
		
		private string _DOMAIN_CODE;
		
		private string _DOMAIN_NAME;
		
		private System.Nullable<System.DateTime> _START_DATE;
		
		private System.Nullable<System.DateTime> _END_DATE;
		
		private string _NOTES;
		
		private string _RECORD_STATUS;
		
		private string _MAKER_ID;
		
		private System.Nullable<System.DateTime> _CREATE_DT;
		
		private string _AUTH_STATUS;
		
		private string _CHECKER_ID;
		
		private System.Nullable<System.DateTime> _APPROVE_DT;
		
		private System.Nullable<System.DateTime> _EDIT_DATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDOMAIN_IDChanging(string value);
    partial void OnDOMAIN_IDChanged();
    partial void OnDOMAIN_CODEChanging(string value);
    partial void OnDOMAIN_CODEChanged();
    partial void OnDOMAIN_NAMEChanging(string value);
    partial void OnDOMAIN_NAMEChanged();
    partial void OnSTART_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSTART_DATEChanged();
    partial void OnEND_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnEND_DATEChanged();
    partial void OnNOTESChanging(string value);
    partial void OnNOTESChanged();
    partial void OnRECORD_STATUSChanging(string value);
    partial void OnRECORD_STATUSChanged();
    partial void OnMAKER_IDChanging(string value);
    partial void OnMAKER_IDChanged();
    partial void OnCREATE_DTChanging(System.Nullable<System.DateTime> value);
    partial void OnCREATE_DTChanged();
    partial void OnAUTH_STATUSChanging(string value);
    partial void OnAUTH_STATUSChanged();
    partial void OnCHECKER_IDChanging(string value);
    partial void OnCHECKER_IDChanged();
    partial void OnAPPROVE_DTChanging(System.Nullable<System.DateTime> value);
    partial void OnAPPROVE_DTChanged();
    partial void OnEDIT_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnEDIT_DATEChanged();
    #endregion
		
		public CM_DOMAIN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOMAIN_ID", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string DOMAIN_ID
		{
			get
			{
				return this._DOMAIN_ID;
			}
			set
			{
				if ((this._DOMAIN_ID != value))
				{
					this.OnDOMAIN_IDChanging(value);
					this.SendPropertyChanging();
					this._DOMAIN_ID = value;
					this.SendPropertyChanged("DOMAIN_ID");
					this.OnDOMAIN_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOMAIN_CODE", DbType="VarChar(50)")]
		public string DOMAIN_CODE
		{
			get
			{
				return this._DOMAIN_CODE;
			}
			set
			{
				if ((this._DOMAIN_CODE != value))
				{
					this.OnDOMAIN_CODEChanging(value);
					this.SendPropertyChanging();
					this._DOMAIN_CODE = value;
					this.SendPropertyChanged("DOMAIN_CODE");
					this.OnDOMAIN_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOMAIN_NAME", DbType="NVarChar(50)")]
		public string DOMAIN_NAME
		{
			get
			{
				return this._DOMAIN_NAME;
			}
			set
			{
				if ((this._DOMAIN_NAME != value))
				{
					this.OnDOMAIN_NAMEChanging(value);
					this.SendPropertyChanging();
					this._DOMAIN_NAME = value;
					this.SendPropertyChanged("DOMAIN_NAME");
					this.OnDOMAIN_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_START_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> START_DATE
		{
			get
			{
				return this._START_DATE;
			}
			set
			{
				if ((this._START_DATE != value))
				{
					this.OnSTART_DATEChanging(value);
					this.SendPropertyChanging();
					this._START_DATE = value;
					this.SendPropertyChanged("START_DATE");
					this.OnSTART_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_END_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> END_DATE
		{
			get
			{
				return this._END_DATE;
			}
			set
			{
				if ((this._END_DATE != value))
				{
					this.OnEND_DATEChanging(value);
					this.SendPropertyChanging();
					this._END_DATE = value;
					this.SendPropertyChanged("END_DATE");
					this.OnEND_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTES", DbType="NVarChar(1000)")]
		public string NOTES
		{
			get
			{
				return this._NOTES;
			}
			set
			{
				if ((this._NOTES != value))
				{
					this.OnNOTESChanging(value);
					this.SendPropertyChanging();
					this._NOTES = value;
					this.SendPropertyChanged("NOTES");
					this.OnNOTESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECORD_STATUS", DbType="VarChar(1)")]
		public string RECORD_STATUS
		{
			get
			{
				return this._RECORD_STATUS;
			}
			set
			{
				if ((this._RECORD_STATUS != value))
				{
					this.OnRECORD_STATUSChanging(value);
					this.SendPropertyChanging();
					this._RECORD_STATUS = value;
					this.SendPropertyChanged("RECORD_STATUS");
					this.OnRECORD_STATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKER_ID", DbType="VarChar(15)")]
		public string MAKER_ID
		{
			get
			{
				return this._MAKER_ID;
			}
			set
			{
				if ((this._MAKER_ID != value))
				{
					this.OnMAKER_IDChanging(value);
					this.SendPropertyChanging();
					this._MAKER_ID = value;
					this.SendPropertyChanged("MAKER_ID");
					this.OnMAKER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATE_DT", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATE_DT
		{
			get
			{
				return this._CREATE_DT;
			}
			set
			{
				if ((this._CREATE_DT != value))
				{
					this.OnCREATE_DTChanging(value);
					this.SendPropertyChanging();
					this._CREATE_DT = value;
					this.SendPropertyChanged("CREATE_DT");
					this.OnCREATE_DTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AUTH_STATUS", DbType="VarChar(50)")]
		public string AUTH_STATUS
		{
			get
			{
				return this._AUTH_STATUS;
			}
			set
			{
				if ((this._AUTH_STATUS != value))
				{
					this.OnAUTH_STATUSChanging(value);
					this.SendPropertyChanging();
					this._AUTH_STATUS = value;
					this.SendPropertyChanged("AUTH_STATUS");
					this.OnAUTH_STATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHECKER_ID", DbType="VarChar(15)")]
		public string CHECKER_ID
		{
			get
			{
				return this._CHECKER_ID;
			}
			set
			{
				if ((this._CHECKER_ID != value))
				{
					this.OnCHECKER_IDChanging(value);
					this.SendPropertyChanging();
					this._CHECKER_ID = value;
					this.SendPropertyChanged("CHECKER_ID");
					this.OnCHECKER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPROVE_DT", DbType="DateTime")]
		public System.Nullable<System.DateTime> APPROVE_DT
		{
			get
			{
				return this._APPROVE_DT;
			}
			set
			{
				if ((this._APPROVE_DT != value))
				{
					this.OnAPPROVE_DTChanging(value);
					this.SendPropertyChanging();
					this._APPROVE_DT = value;
					this.SendPropertyChanged("APPROVE_DT");
					this.OnAPPROVE_DTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDIT_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> EDIT_DATE
		{
			get
			{
				return this._EDIT_DATE;
			}
			set
			{
				if ((this._EDIT_DATE != value))
				{
					this.OnEDIT_DATEChanging(value);
					this.SendPropertyChanging();
					this._EDIT_DATE = value;
					this.SendPropertyChanged("EDIT_DATE");
					this.OnEDIT_DATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class CM_DOMAIN_InsResult
	{
		
		private string _Result;
		
		private string _DOMAIN_ID;
		
		private string _ErrorDesc;
		
		public CM_DOMAIN_InsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Result", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string Result
		{
			get
			{
				return this._Result;
			}
			set
			{
				if ((this._Result != value))
				{
					this._Result = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOMAIN_ID", DbType="VarChar(15)")]
		public string DOMAIN_ID
		{
			get
			{
				return this._DOMAIN_ID;
			}
			set
			{
				if ((this._DOMAIN_ID != value))
				{
					this._DOMAIN_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorDesc", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string ErrorDesc
		{
			get
			{
				return this._ErrorDesc;
			}
			set
			{
				if ((this._ErrorDesc != value))
				{
					this._ErrorDesc = value;
				}
			}
		}
	}
	
	public partial class CM_DOMAIN_ListResult
	{
		
		private string _BRANCH_ID;
		
		private string _FATHER_ID;
		
		private string _IS_POTENTIAL;
		
		private string _BRANCH_CODE;
		
		private string _BRANCH_NAME;
		
		private string _DAO_CODE;
		
		private string _DAO_NAME;
		
		private string _REGION_ID;
		
		private string _BRANCH_TYPE;
		
		private string _ADDR;
		
		private string _PROVICE;
		
		private string _TEL;
		
		private string _TAX_NO;
		
		private string _NOTES;
		
		private string _RECORD_STATUS;
		
		private string _MAKER_ID;
		
		private System.Nullable<System.DateTime> _CREATE_DT;
		
		private string _AUTH_STATUS;
		
		private string _CHECKER_ID;
		
		private System.Nullable<System.DateTime> _APPROVE_DT;
		
		public CM_DOMAIN_ListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCH_ID", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string BRANCH_ID
		{
			get
			{
				return this._BRANCH_ID;
			}
			set
			{
				if ((this._BRANCH_ID != value))
				{
					this._BRANCH_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FATHER_ID", DbType="VarChar(15)")]
		public string FATHER_ID
		{
			get
			{
				return this._FATHER_ID;
			}
			set
			{
				if ((this._FATHER_ID != value))
				{
					this._FATHER_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IS_POTENTIAL", DbType="VarChar(1)")]
		public string IS_POTENTIAL
		{
			get
			{
				return this._IS_POTENTIAL;
			}
			set
			{
				if ((this._IS_POTENTIAL != value))
				{
					this._IS_POTENTIAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCH_CODE", DbType="VarChar(10)")]
		public string BRANCH_CODE
		{
			get
			{
				return this._BRANCH_CODE;
			}
			set
			{
				if ((this._BRANCH_CODE != value))
				{
					this._BRANCH_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCH_NAME", DbType="NVarChar(200)")]
		public string BRANCH_NAME
		{
			get
			{
				return this._BRANCH_NAME;
			}
			set
			{
				if ((this._BRANCH_NAME != value))
				{
					this._BRANCH_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DAO_CODE", DbType="VarChar(40)")]
		public string DAO_CODE
		{
			get
			{
				return this._DAO_CODE;
			}
			set
			{
				if ((this._DAO_CODE != value))
				{
					this._DAO_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DAO_NAME", DbType="NVarChar(500)")]
		public string DAO_NAME
		{
			get
			{
				return this._DAO_NAME;
			}
			set
			{
				if ((this._DAO_NAME != value))
				{
					this._DAO_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REGION_ID", DbType="VarChar(15)")]
		public string REGION_ID
		{
			get
			{
				return this._REGION_ID;
			}
			set
			{
				if ((this._REGION_ID != value))
				{
					this._REGION_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCH_TYPE", DbType="VarChar(5)")]
		public string BRANCH_TYPE
		{
			get
			{
				return this._BRANCH_TYPE;
			}
			set
			{
				if ((this._BRANCH_TYPE != value))
				{
					this._BRANCH_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDR", DbType="NVarChar(200)")]
		public string ADDR
		{
			get
			{
				return this._ADDR;
			}
			set
			{
				if ((this._ADDR != value))
				{
					this._ADDR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROVICE", DbType="NVarChar(500)")]
		public string PROVICE
		{
			get
			{
				return this._PROVICE;
			}
			set
			{
				if ((this._PROVICE != value))
				{
					this._PROVICE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEL", DbType="VarChar(20)")]
		public string TEL
		{
			get
			{
				return this._TEL;
			}
			set
			{
				if ((this._TEL != value))
				{
					this._TEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAX_NO", DbType="VarChar(50)")]
		public string TAX_NO
		{
			get
			{
				return this._TAX_NO;
			}
			set
			{
				if ((this._TAX_NO != value))
				{
					this._TAX_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTES", DbType="NVarChar(1000)")]
		public string NOTES
		{
			get
			{
				return this._NOTES;
			}
			set
			{
				if ((this._NOTES != value))
				{
					this._NOTES = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECORD_STATUS", DbType="VarChar(1)")]
		public string RECORD_STATUS
		{
			get
			{
				return this._RECORD_STATUS;
			}
			set
			{
				if ((this._RECORD_STATUS != value))
				{
					this._RECORD_STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKER_ID", DbType="VarChar(15)")]
		public string MAKER_ID
		{
			get
			{
				return this._MAKER_ID;
			}
			set
			{
				if ((this._MAKER_ID != value))
				{
					this._MAKER_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATE_DT", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATE_DT
		{
			get
			{
				return this._CREATE_DT;
			}
			set
			{
				if ((this._CREATE_DT != value))
				{
					this._CREATE_DT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AUTH_STATUS", DbType="VarChar(50)")]
		public string AUTH_STATUS
		{
			get
			{
				return this._AUTH_STATUS;
			}
			set
			{
				if ((this._AUTH_STATUS != value))
				{
					this._AUTH_STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHECKER_ID", DbType="VarChar(15)")]
		public string CHECKER_ID
		{
			get
			{
				return this._CHECKER_ID;
			}
			set
			{
				if ((this._CHECKER_ID != value))
				{
					this._CHECKER_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPROVE_DT", DbType="DateTime")]
		public System.Nullable<System.DateTime> APPROVE_DT
		{
			get
			{
				return this._APPROVE_DT;
			}
			set
			{
				if ((this._APPROVE_DT != value))
				{
					this._APPROVE_DT = value;
				}
			}
		}
	}
	
	public partial class CM_DOMAIN_SearchResult
	{
		
		private string _DOMAIN_ID;
		
		private string _DOMAIN_CODE;
		
		private string _DOMAIN_NAME;
		
		private System.Nullable<System.DateTime> _START_DATE;
		
		private System.Nullable<System.DateTime> _END_DATE;
		
		private string _NOTES;
		
		private string _RECORD_STATUS;
		
		private string _MAKER_ID;
		
		private System.Nullable<System.DateTime> _CREATE_DT;
		
		private string _AUTH_STATUS;
		
		private string _CHECKER_ID;
		
		private System.Nullable<System.DateTime> _APPROVE_DT;
		
		private System.Nullable<System.DateTime> _EDIT_DATE;
		
		public CM_DOMAIN_SearchResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOMAIN_ID", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string DOMAIN_ID
		{
			get
			{
				return this._DOMAIN_ID;
			}
			set
			{
				if ((this._DOMAIN_ID != value))
				{
					this._DOMAIN_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOMAIN_CODE", DbType="VarChar(50)")]
		public string DOMAIN_CODE
		{
			get
			{
				return this._DOMAIN_CODE;
			}
			set
			{
				if ((this._DOMAIN_CODE != value))
				{
					this._DOMAIN_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOMAIN_NAME", DbType="NVarChar(50)")]
		public string DOMAIN_NAME
		{
			get
			{
				return this._DOMAIN_NAME;
			}
			set
			{
				if ((this._DOMAIN_NAME != value))
				{
					this._DOMAIN_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_START_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> START_DATE
		{
			get
			{
				return this._START_DATE;
			}
			set
			{
				if ((this._START_DATE != value))
				{
					this._START_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_END_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> END_DATE
		{
			get
			{
				return this._END_DATE;
			}
			set
			{
				if ((this._END_DATE != value))
				{
					this._END_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTES", DbType="NVarChar(1000)")]
		public string NOTES
		{
			get
			{
				return this._NOTES;
			}
			set
			{
				if ((this._NOTES != value))
				{
					this._NOTES = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECORD_STATUS", DbType="VarChar(1)")]
		public string RECORD_STATUS
		{
			get
			{
				return this._RECORD_STATUS;
			}
			set
			{
				if ((this._RECORD_STATUS != value))
				{
					this._RECORD_STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKER_ID", DbType="VarChar(15)")]
		public string MAKER_ID
		{
			get
			{
				return this._MAKER_ID;
			}
			set
			{
				if ((this._MAKER_ID != value))
				{
					this._MAKER_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATE_DT", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATE_DT
		{
			get
			{
				return this._CREATE_DT;
			}
			set
			{
				if ((this._CREATE_DT != value))
				{
					this._CREATE_DT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AUTH_STATUS", DbType="VarChar(50)")]
		public string AUTH_STATUS
		{
			get
			{
				return this._AUTH_STATUS;
			}
			set
			{
				if ((this._AUTH_STATUS != value))
				{
					this._AUTH_STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHECKER_ID", DbType="VarChar(15)")]
		public string CHECKER_ID
		{
			get
			{
				return this._CHECKER_ID;
			}
			set
			{
				if ((this._CHECKER_ID != value))
				{
					this._CHECKER_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPROVE_DT", DbType="DateTime")]
		public System.Nullable<System.DateTime> APPROVE_DT
		{
			get
			{
				return this._APPROVE_DT;
			}
			set
			{
				if ((this._APPROVE_DT != value))
				{
					this._APPROVE_DT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDIT_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> EDIT_DATE
		{
			get
			{
				return this._EDIT_DATE;
			}
			set
			{
				if ((this._EDIT_DATE != value))
				{
					this._EDIT_DATE = value;
				}
			}
		}
	}
	
	public partial class CM_DOMAIN_UpdResult
	{
		
		private string _Result;
		
		private string _DOMAIN_ID;
		
		private string _ErrorDesc;
		
		public CM_DOMAIN_UpdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Result", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Result
		{
			get
			{
				return this._Result;
			}
			set
			{
				if ((this._Result != value))
				{
					this._Result = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOMAIN_ID", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string DOMAIN_ID
		{
			get
			{
				return this._DOMAIN_ID;
			}
			set
			{
				if ((this._DOMAIN_ID != value))
				{
					this._DOMAIN_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorDesc", DbType="NVarChar(1000)")]
		public string ErrorDesc
		{
			get
			{
				return this._ErrorDesc;
			}
			set
			{
				if ((this._ErrorDesc != value))
				{
					this._ErrorDesc = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
